#Useful NLP Libraries & Networks

# Question 1: Compare and contrast NLTK and spaCy in terms of features, ease of use, and performance.


# Comparison of NLTK and spaCy

| Feature | NLTK | spaCy |
|---------|------|--------|
| **Primary Purpose** | Education and research | Production and industrial applications |
| **Ease of Use** | Beginner-friendly but often requires more code | Simple and intuitive API with fewer lines of code |
| **Performance** | Slower for large datasets | Much faster and optimized for high performance |
| **Speed** | Moderate | Very fast |
| **Built-in Datasets** | Large collection of corpora and datasets | Limited built-in datasets |
| **Tokenization** | Available | Faster and more efficient |
| **Lemmatization** | Supported | Supported with better optimization |
| **Named Entity Recognition (NER)** | Available but basic | More accurate and efficient |
| **Deep Learning Support** | Limited | Excellent support through modern pipelines |
| **Best For** | Learning NLP, education, research | Real-world NLP systems and production applications |





# Question 2: What is TextBlob and how does it simplify common NLP tasks like sentiment analysis and translation?


**TextBlob** is a simple and user-friendly Python library built on top of **NLTK (Natural Language Toolkit)**. It provides an easy interface for performing common **Natural Language Processing (NLP)** tasks without requiring complex code.

TextBlob is especially suitable for beginners because it allows developers to perform various NLP operations with just a few lines of Python code.



# How TextBlob Simplifies Sentiment Analysis

**Sentiment Analysis** is the process of determining whether a piece of text expresses a **positive, negative, or neutral** opinion.

TextBlob automatically calculates two important values:

### 1. Polarity

- Range: **-1 to +1**
- **-1** → Negative sentiment
- **0** → Neutral sentiment
- **+1** → Positive sentiment

### 2. Subjectivity

- Range: **0 to 1**
- **0** → Objective (fact-based)
- **1** → Subjective (opinion-based)

### Example

**Text:**
```
"The customer service is excellent."
```

Output:

- Polarity = Positive
- Subjectivity = High

This makes it easy to analyze customer reviews, product feedback, and social media posts.



# How TextBlob Simplifies Translation

TextBlob also provides built-in support for **language translation**.

It can translate text from one language to another using translation services.

### Example

English:
```
Good Morning
```

Hindi:
```
सुप्रभात
```

This feature is useful for multilingual applications, chatbots, customer support systems, and international communication.



# Question 3: Explain the role of Stanford NLP in academic and industry NLP projects.



# Role of Stanford NLP in Academic Projects

Stanford NLP plays an important role in education and research because it provides accurate and reliable NLP tools for language analysis.

### Major Uses in Academia

- Research in Natural Language Processing.
- Language modeling and linguistic analysis.
- Machine Translation research.
- Information Extraction.
- Text Classification.
- Named Entity Recognition (NER).
- Question Answering Systems.
- Sentiment Analysis.
- Development and evaluation of new NLP algorithms.

Researchers use Stanford NLP to study grammar, sentence structure, semantics, and language understanding while developing new AI techniques.

---

# Role of Stanford NLP in Industry Projects

Stanford NLP is widely used in industry to build intelligent language-processing applications that improve business operations and customer experiences.

### Major Industry Applications

- Chatbots and Virtual Assistants.
- Customer Support Automation.
- Search Engines.
- Email Spam Detection.
- Sentiment Analysis of customer reviews.
- Social Media Monitoring.
- Document Classification.
- Information Extraction.
- Recommendation Systems.
- Machine Translation.

Many companies use Stanford NLP to analyze large volumes of text data and extract meaningful insights for decision-making.



# Question 4: Describe the architecture and functioning of a Recurrent Neural Network (RNN).

# Architecture of a Recurrent Neural Network (RNN)

An RNN consists of the following main components:

### 1. Input Layer

The input layer receives sequential data one element at a time.

Examples:

- Words in a sentence
- Audio signals
- Stock prices
- Weather data

Each input at a time step is represented as **xₜ**.



### 2. Hidden Layer

The hidden layer is the core component of an RNN.

At every time step, it receives:

- The current input (**xₜ**)
- The hidden state from the previous time step (**hₜ₋₁**)

Using both pieces of information, it computes a new hidden state (**hₜ**). This hidden state acts as the network's memory, allowing information from earlier time steps to influence future predictions.



### 3. Recurrent Connection

The hidden layer has a feedback (recurrent) connection that passes the hidden state from one time step to the next.

This enables the network to remember previous information and capture dependencies in sequential data.


### 4. Output Layer

The output layer generates the prediction for each time step.

Depending on the application, the output may be:

- One output after processing the entire sequence (e.g., sentiment analysis)
- One output for every time step (e.g., language translation)



# Working of an RNN

The functioning of an RNN can be explained in the following steps:

### Step 1: Receive Sequential Input

The network receives the first input (**x₁**) and initializes the hidden state.



### Step 2: Compute Hidden State

The current input and the previous hidden state are combined to compute a new hidden state.

This hidden state stores information from previous inputs.



### Step 3: Generate Output

The hidden state is used to produce the output for the current time step.



### Step 4: Pass Memory Forward

The hidden state is passed to the next time step, allowing the network to remember previous information.



### Step 5: Repeat for Entire Sequence

The above process continues until all elements of the sequence have been processed.



# Question 5: What is the key difference between LSTM and GRU networks in NLP applications?



| Feature | LSTM | GRU |
|---------|------|-----|
| **Full Form** | Long Short-Term Memory | Gated Recurrent Unit |
| **Memory Cell** | Yes | No |
| **Number of Gates** | Three (Forget, Input, Output) | Two (Update, Reset) |
| **Hidden State** | Hidden state and cell state | Hidden state only |
| **Architecture** | More complex | Simpler |
| **Number of Parameters** | More | Fewer |
| **Training Speed** | Slower | Faster |
| **Memory Usage** | Higher | Lower |
| **Performance on Long Sequences** | Generally better | Good, but may be slightly less effective on very long sequences |
| **Best Use Cases** | Complex NLP tasks with long dependencies | Faster NLP applications and smaller datasets |



In [1]:
# Question 6
# Perform Sentiment Analysis using TextBlob

# Import TextBlob
from textblob import TextBlob

# Input paragraph
text = """
I had a great experience using the new mobile banking app.
The interface is intuitive, and customer support was quick to resolve my issue.
However, the app did crash once during a transaction, which was frustrating.
"""

# Create a TextBlob object
blob = TextBlob(text)

# Perform sentiment analysis
sentiment = blob.sentiment

# Print the results
print("Sentiment Analysis Results")
print("-" * 35)

print("Polarity Score    :", sentiment.polarity)
print("Subjectivity Score:", sentiment.subjectivity)

# Interpret the polarity
if sentiment.polarity > 0:
    print("\nOverall Sentiment : Positive")
elif sentiment.polarity < 0:
    print("\nOverall Sentiment : Negative")
else:
    print("\nOverall Sentiment : Neutral")

Sentiment Analysis Results
-----------------------------------
Polarity Score    : 0.21742424242424244
Subjectivity Score: 0.6511363636363636

Overall Sentiment : Positive


In [4]:
# Question 7
# Perform String Tokenization and Frequency Distribution using Python and NLTK

# Import required libraries
import nltk
from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist

# Download required NLTK resources (Run only once)
nltk.download('punkt')
nltk.download('punkt_tab')

# Sample paragraph
text = """
Natural Language Processing (NLP) is a fascinating field that combines linguistics,
computer science, and artificial intelligence. It enables machines to understand,
interpret, and generate human language. Applications of NLP include chatbots,
sentiment analysis, and machine translation. As technology advances, the role of NLP
in modern solutions is becoming increasingly critical.
"""

# Convert text to lowercase
text = text.lower()

# Tokenize the text into words
tokens = word_tokenize(text)

# Display word tokens
print("Word Tokens:\n")
print(tokens)

# Create frequency distribution
freq_dist = FreqDist(tokens)

# Display frequency distribution
print("\nWord Frequency Distribution:\n")
for word, frequency in freq_dist.items():
    print(f"{word} : {frequency}")

# Display the 10 most common words
print("\nTop 10 Most Frequent Words:\n")
print(freq_dist.most_common(10))

Word Tokens:

['natural', 'language', 'processing', '(', 'nlp', ')', 'is', 'a', 'fascinating', 'field', 'that', 'combines', 'linguistics', ',', 'computer', 'science', ',', 'and', 'artificial', 'intelligence', '.', 'it', 'enables', 'machines', 'to', 'understand', ',', 'interpret', ',', 'and', 'generate', 'human', 'language', '.', 'applications', 'of', 'nlp', 'include', 'chatbots', ',', 'sentiment', 'analysis', ',', 'and', 'machine', 'translation', '.', 'as', 'technology', 'advances', ',', 'the', 'role', 'of', 'nlp', 'in', 'modern', 'solutions', 'is', 'becoming', 'increasingly', 'critical', '.']

Word Frequency Distribution:

natural : 1
language : 2
processing : 1
( : 1
nlp : 3
) : 1
is : 2
a : 1
fascinating : 1
field : 1
that : 1
combines : 1
linguistics : 1
, : 7
computer : 1
science : 1
and : 3
artificial : 1
intelligence : 1
. : 4
it : 1
enables : 1
machines : 1
to : 1
understand : 1
interpret : 1
generate : 1
human : 1
applications : 1
of : 2
include : 1
chatbots : 1
sentiment : 1


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [5]:
# Question 8
# Build a basic LSTM model in Keras for text classification

# Import required libraries
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# -----------------------------
# Dataset
# -----------------------------
texts = [
    "I love this project",                # Positive
    "This is an amazing experience",      # Positive
    "I hate waiting in line",             # Negative
    "This is the worst service",          # Negative
    "Absolutely fantastic!"               # Positive
]

labels = [1, 1, 0, 0, 1]

# -----------------------------
# Text Preprocessing
# -----------------------------

# Initialize tokenizer
tokenizer = Tokenizer()

# Build vocabulary
tokenizer.fit_on_texts(texts)

# Convert text to sequences
sequences = tokenizer.texts_to_sequences(texts)

# Pad sequences to equal length
max_length = max(len(seq) for seq in sequences)
X = pad_sequences(sequences, maxlen=max_length, padding="post")

# Convert labels to NumPy array
y = np.array(labels)

# Display tokenized sequences
print("Tokenized Sequences:\n")
print(X)

# -----------------------------
# Build LSTM Model
# -----------------------------

model = Sequential([
    Embedding(
        input_dim=len(tokenizer.word_index) + 1,
        output_dim=16
    ),

    LSTM(32),

    Dense(1, activation="sigmoid")
])

# Compile the model
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

# -----------------------------
# Train the Model
# -----------------------------

history = model.fit(
    X,
    y,
    epochs=20,
    batch_size=2,
    verbose=1
)

# -----------------------------
# Evaluate the Model
# -----------------------------

loss, accuracy = model.evaluate(X, y, verbose=0)

print("\nTraining Accuracy: {:.2f}%".format(accuracy * 100))

Tokenized Sequences:

[[ 2  4  1  5  0]
 [ 1  3  6  7  8]
 [ 2  9 10 11 12]
 [ 1  3 13 14 15]
 [16 17  0  0  0]]
Epoch 1/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 1.0000 - loss: 0.6901
Epoch 2/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.6865
Epoch 3/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8000 - loss: 0.6830
Epoch 4/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6000 - loss: 0.6807
Epoch 5/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6000 - loss: 0.6746    
Epoch 6/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6000 - loss: 0.6707
Epoch 7/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6000 - loss: 0.6663
Epoch 8/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6000 - loss: 0.6599
Epoch 9/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8000 - loss: 0.6529
Epoch 10/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8000 - loss: 0.6444
Epoch 11/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - 

In [6]:
# Question 9
# Build a simple NLP pipeline using spaCy:
# Tokenization, Lemmatization, and Named Entity Recognition (NER)

# Import spaCy
import spacy

# Load the English language model
nlp = spacy.load("en_core_web_sm")

# Input paragraph
text = """
Homi Jehangir Bhaba was an Indian nuclear physicist who played a key role in the
development of India's atomic energy program. He was the founding director of the
Tata Institute of Fundamental Research (TIFR) and was instrumental in establishing
the Atomic Energy Commission of India.
"""

# Process the text
doc = nlp(text)

# ----------------------------------------
# Tokenization
# ----------------------------------------

print("TOKENS\n")

for token in doc:
    print(token.text)

# ----------------------------------------
# Lemmatization
# ----------------------------------------

print("\n" + "="*50)
print("LEMMATIZATION\n")

for token in doc:
    print(f"{token.text:<20} --> {token.lemma_}")

# ----------------------------------------
# Named Entity Recognition (NER)
# ----------------------------------------

print("\n" + "="*50)
print("NAMED ENTITIES\n")

for entity in doc.ents:
    print(f"{entity.text:<50} {entity.label_}")

TOKENS



Homi
Jehangir
Bhaba
was
an
Indian
nuclear
physicist
who
played
a
key
role
in
the


development
of
India
's
atomic
energy
program
.
He
was
the
founding
director
of
the


Tata
Institute
of
Fundamental
Research
(
TIFR
)
and
was
instrumental
in
establishing


the
Atomic
Energy
Commission
of
India
.



LEMMATIZATION


                    --> 

Homi                 --> Homi
Jehangir             --> Jehangir
Bhaba                --> Bhaba
was                  --> be
an                   --> an
Indian               --> indian
nuclear              --> nuclear
physicist            --> physicist
who                  --> who
played               --> play
a                    --> a
key                  --> key
role                 --> role
in                   --> in
the                  --> the

                    --> 

development          --> development
of                   --> of
India                --> India
's                   --> 's
atomic               --> atomic
energy       

# Question 10: Mental Health Chatbot using LSTM/GRU and spaCy

## Problem Statement

A mental health platform requires an intelligent chatbot that can understand user messages, identify their intent, and generate appropriate responses. The chatbot should accurately process natural language while ensuring user privacy and providing supportive interactions.



# System Architecture

The chatbot can be built using the following components:

1. **User Input**
   - The user enters a message through a web or mobile application.

2. **Text Preprocessing (spaCy / Stanford NLP)**
   - Tokenization
   - Lowercasing
   - Lemmatization
   - Stop-word removal
   - Named Entity Recognition (NER)

3. **Word Embedding**
   - Convert text into numerical vectors using an Embedding layer.

4. **Sequence Model**
   - Use an **LSTM** or **GRU** network to learn the context and sequence of words.

5. **Dense Output Layer**
   - Classify the user's intent (e.g., stress, anxiety, sadness, greeting, or general conversation).

6. **Response Generation**
   - Return the most suitable predefined or generated response.



# Data Preprocessing Pipeline

The text is processed through the following steps:

- Convert text to lowercase.
- Remove punctuation and special characters.
- Tokenize the sentence.
- Remove stop words.
- Perform lemmatization.
- Convert words into integer sequences.
- Pad sequences to equal length before feeding them to the neural network.



# Why Use LSTM or GRU?

### LSTM

- Learns long-term dependencies.
- Handles long conversations effectively.
- Suitable for complex dialogue systems.

### GRU

- Simpler architecture.
- Faster training.
- Uses fewer parameters.
- Suitable for lightweight chatbot applications.



# Why Use spaCy?

spaCy provides powerful NLP preprocessing features such as:

- Tokenization
- Lemmatization
- Part-of-Speech Tagging
- Named Entity Recognition (NER)

These features help clean and structure user input before it is passed to the neural network.



# Ethical Considerations

A mental health chatbot should follow important ethical principles:

- Protect user privacy and confidential information.
- Securely store conversation data.
- Avoid giving medical diagnoses.
- Clearly inform users that the chatbot is not a replacement for a licensed mental health professional.
- Detect crisis-related messages and recommend immediate contact with emergency services or mental health professionals.
- Minimize bias by training on diverse and representative datasets.



# Business Benefits

- Provides 24/7 support.
- Reduces response time.
- Improves user engagement.
- Assists mental health professionals by handling routine conversations.
- Enhances accessibility to mental health resources.



# Conclusion

A chatbot built with **spaCy** for preprocessing and an **LSTM or GRU** network for sequence learning can effectively understand user messages and provide relevant responses. Combining robust NLP techniques with responsible ethical practices results in a reliable and user-friendly mental health support system.

In [7]:
import spacy
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Load spaCy English model
nlp = spacy.load("en_core_web_sm")

# Sample dataset
texts = [
    "I feel very happy today",
    "I am feeling sad",
    "I have anxiety",
    "I feel stressed",
    "Hello",
    "Good morning"
]

# Intent labels
labels = [1, 2, 3, 4, 0, 0]

# Text preprocessing using spaCy
processed_texts = []

for sentence in texts:
    doc = nlp(sentence.lower())

    words = [
        token.lemma_
        for token in doc
        if not token.is_stop and not token.is_punct
    ]

    processed_texts.append(" ".join(words))

print("Processed Text:")
print(processed_texts)

# Tokenization
tokenizer = Tokenizer()
tokenizer.fit_on_texts(processed_texts)

sequences = tokenizer.texts_to_sequences(processed_texts)

# Padding
max_length = max(len(seq) for seq in sequences)
X = pad_sequences(sequences, maxlen=max_length, padding="post")

y = np.array(labels)

# Build LSTM Model
model = Sequential([
    Embedding(input_dim=len(tokenizer.word_index) + 1,
              output_dim=16),

    LSTM(32),

    Dense(16, activation="relu"),

    Dense(5, activation="softmax")
])

# Compile Model
model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# Train Model
history = model.fit(
    X,
    y,
    epochs=20,
    batch_size=2,
    verbose=1
)

# Evaluate Model
loss, accuracy = model.evaluate(X, y, verbose=0)

print("\nTraining Accuracy: {:.2f}%".format(accuracy * 100))

Processed Text:
['feel happy today', 'feel sad', 'anxiety', 'feel stressed', 'hello', 'good morning']
Epoch 1/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.0000e+00 - loss: 1.6091
Epoch 2/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3333 - loss: 1.6050 
Epoch 3/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3333 - loss: 1.6030
Epoch 4/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3333 - loss: 1.5998     
Epoch 5/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5000 - loss: 1.5978
Epoch 6/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5000 - loss: 1.5944 
Epoch 7/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5000 - loss: 1.5914     
Epoch 8/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5000 - loss: 1.5888 
Epoch 9/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5000 - loss: 1.5857 
Epoch 10/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5000 - loss: 1.5813 
Epoch 11/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accu